language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

sudo: false

before_install: "composer install"

script: "vendor/bin/phpunit"

martix:
    allow_failures:
        - php: hhvm
    fast_finish: true